FROM golang:alpine as build-env
RUN apk --no-cache add git
RUN go get github.com/cloudspannerecosystem/spanner-cli

FROM alpine:3.11.5
WORKDIR /go/bin
COPY --from=build-env /go/bin/spanner-cli /go/bin/spanner-cli
COPY wrap wrap
