version: "3.4"

services:
  spanner-emulator:
    image: gcr.io/cloud-spanner-emulator/emulator:0.7.3
    networks:
      spanner:
        aliases:
          - spanner.localhost
  gcloud-tools:
    depends_on:
      - spanner-emulator
    build:
      context: .
      dockerfile: Dockerfile-gcloud
    env_file:
      - .env
    networks:
      - spanner
  spanner-cli:
    build:
      context: .
      dockerfile: Dockerfile-cli
    env_file:
      - .env
    networks:
      - spanner

networks:
  spanner:
    external: true
